MyfirstWebApplication5/Models/Stock.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyfirstWebApplication5.Models
{
    public class Stock
    {
        public int Stock_Id { get; set; }
        public string Stock_Name { get; set; }
    }
}

MyfirstWebApplication5/Controllers/StockController.cs
using MyfirstWebApplication5.Config;
using MyfirstWebApplication5.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using ClosedXML.Excel;
using System.Text.RegularExpressions;

namespace MyfirstWebApplication5.Controllers
{
    public class StockController : Controller
    {
       
        //ここからスタート(ActionResultとviewの名前をそろえる)
        public ActionResult GetAll()
        {
            return View();
        }

        public JsonResult GetStockJson()
        {

            List<Stock> stocks = new List<Stock>();
            return Json(stocks, JsonRequestBehavior.AllowGet);

        }

       
        //検索ボタン押下後
        public ActionResult Search(string search,int ? page,string select_stock)
        {


            //searchderedirect
            if (search == null) search = ""; // nullが渡されたら""を入れる

            //erakaihi
            if (select_stock == null) select_stock = "1";

            

            ViewBag.kassei = 1;

            List<Stock> stocks = GetStocks("Stocks_Search", search, select_stock);

            if(page > 0)
            {
                page = page;
            }
            else
            {
                page = 1;
            } 

            int limit = 50;
            int start = (int)(page - 1) * limit;
            int totalCount = stocks.Count();
            ViewBag.totalCount = totalCount;
            ViewBag.pageCurrent = page;

            int numberPage = (totalCount / limit);
            ViewBag.numberPage = numberPage;

            ViewBag.select_stock = select_stock;

            ViewBag.search = search;




            var data = stocks.Skip(start).Take(limit);
            //var data = stocks.OrderByDescending(s => s.Stock_Id).Skip(start).Take(limit);


            return View("GetAll", data);
            
            //return RedirectToAction("GetAll", data);
        }

        [HttpPost]
        public JsonResult test(string td)
        {
            //return Json("true", JsonRequestBehavior.AllowGet);
            return Json(td, JsonRequestBehavior.AllowGet);
        }








        //方針を変えてajaxで取得する、ボタンを押下されたタイミングではSQLが発行されていない
        //ファイル出力
        //[HttpPost]
        //public ActionResult FileOutput(string ntblstock, string select_stock, Stock stockss)
        //{

            public ActionResult FileOutput(string td)
            {

            var strList = new List<string>();
            string[] arr1 = Regex.Split(td, "\r\n|\n");

            foreach (string hairetu in arr1)
            {

                strList.Add(hairetu.Trim());
                strList.Remove("");
                strList.Remove("Edit");
                strList.Remove("Delete");
            }


            //新規のExcelブックを作成する
            var workbook = new XLWorkbook();
            var worksheet = workbook.Worksheets.Add("信用銘柄");


           
            for (var i = 0; i < strList.Count; i++)
            {
                //0から39の範囲内で偶数の場合上奇数の場合下

                if (i % 2 == 0)
                {
                    worksheet.Cell(i + 1, 1).Value = strList[i].ToString();
                }
                
                else
                {
                    worksheet.Cell(i, 2).Value = strList[i].ToString();

                }
                
            }

            //ajax nobaai


            //using (MemoryStream stream = new MemoryStream())
            //{
            //    workbook.SaveAs(stream);
            //    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"ComList_{DateTime.Now.ToString("yyyyMMdd")}.xlsx");
            //}



            workbook.SaveAs(@"C:\Users\ksk\Desktop\プログラミング\C#MVC\youtubestudy\MyfirstWebApplication30\test2.xlsx");

            return RedirectToAction("GetAll");
        }



        public List<Stock> GetStocks(string storeProcedure, string search,string select_stock)
        {
                List<Stock> stocks = new List<Stock>();

           
            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {

                using (SqlCommand cmd = new SqlCommand(storeProcedure, con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;

                    //if (search != null || select_stock != null) 
                        if (search != null)
                        cmd.Parameters.AddWithValue("@Filter", search);
                        cmd.Parameters.AddWithValue("@FilterID", select_stock);


                   
                    if (con.State != System.Data.ConnectionState.Open)
                    {
                        con.Open();

                        SqlDataReader sdr = cmd.ExecuteReader();

                        DataTable dtStocks = new DataTable();

                        dtStocks.Load(sdr);

                        foreach (DataRow row in dtStocks.Rows)
                        {
                            stocks.Add(
                                new Stock
                                {
                                    Stock_Id = Convert.ToInt32(row["CODE"]),
                                    Stock_Name = row["CODENAME"].ToString(),
                                    
                                }

                            );
                        }
                    }

                

                }

                ViewBag.stocks = stocks;
                return stocks;
            
            }
        }

        //Createの初期表示
        public ActionResult Create()
        {
            //新規登録時はCODEを表示させる
            ViewBag.hyouji = 1;
            return View();
        }

        //Createのsubmit押下後
        [HttpPost]
        public ActionResult Create(Stock stock)
        {
            if (ModelState.IsValid)
            {
                using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
                {
                    using (SqlCommand cmd = new SqlCommand("Stock_Save_Update", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@Id", stock.Stock_Id);
                        cmd.Parameters.AddWithValue("@Name", stock.Stock_Name);
                        


                        if (con.State != System.Data.ConnectionState.Open)
                        {
                            con.Open();
                            cmd.ExecuteNonQuery();
                        }

                    }
                    //return RedirectToAction("GetAll");
                    return RedirectToAction("Search");
                }

            }
            //return Content("record save in the database");
            return View("Create", stock);
        }

        //ファイル出力ボタン




        //削除
        public ActionResult Delete(int id)
        {
            if (id < 0)
                return HttpNotFound();

            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {
                using (SqlCommand cmd = new SqlCommand("Stock_DeleteById", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@Id", id);

                    if (con.State != ConnectionState.Open)
                        con.Open();

                    cmd.ExecuteNonQuery();
                }
            }
            return RedirectToAction("GetAll");
        }

        //編集
        public ActionResult Edit(int Id)
        {
            if (Id <= 0)
                return HttpNotFound();

            var _stock = new Stock();

            using (SqlConnection con = new SqlConnection(StoreConnection.GetConnection()))
            {

                using (SqlCommand cmd = new SqlCommand("Stock_GetById", con))
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.AddWithValue("@Id", Id);

                    if (con.State != ConnectionState.Open)
                        con.Open();
                    SqlDataReader sdr = cmd.ExecuteReader();
                    DataTable dt = new DataTable();

                    if (sdr.HasRows)
                    {
                        dt.Load(sdr);

                        DataRow row = dt.Rows[0];
                        _stock.Stock_Id = Convert.ToInt32(row["CODE"]);
                        _stock.Stock_Name = row["CODENAME"].ToString();
                        

                        return View("Create", _stock);

                    }
                    else
                    {
                        return HttpNotFound();
                    }

                }

            }
        }

    }
}

MyfirstWebApplication5/Views/Stock/Create.cshtml
@*@model IEnumerable<MyfirstWebApplication5.Models.Stock>*@
@model MyfirstWebApplication5.Models.Stock

@{              
  ViewBag.Title = "新規登録";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Stock"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Stock_Id, htmlAttributes: new { @class = "control-label col-md-2",  })
        
        <div class="col-md-10">
            @*活性・非活性*@
            @if (ViewBag.hyouji == 1)
            {
                @Html.EditorFor(model => model.Stock_Id, new { htmlAttributes = new { @class = "form-control" } })

            }
            else
            {
                @*@Html.EditorFor(model => model.Stock_Id, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })*@
                @Html.EditorFor(model => model.Stock_Id, new { htmlAttributes = new { @class = "form-control" } })


            }

            @Html.ValidationMessageFor(model => model.Stock_Id, "", new { @class = "text-danger" })
        </div>
    </div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Stock_Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Stock_Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Stock_Name, "", new { @class = "text-danger" })
        </div>
    </div>

</div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="SaveProduct" class="btn btn-primary" />
        </div>
    </div>
}

MyfirstWebApplication5/Views/Stock/GetAll.cshtml
@model IEnumerable<MyfirstWebApplication5.Models.Stock>
@*@model MyfirstWebApplication5.Models.Stock*@
@{
    /**/

    ViewBag.Title = "stock";
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<h2>信用銘柄検索</h2>

<br />
@using (Html.BeginForm("Search", "Stock", FormMethod.Get))
{
    <div class="row">
        <div class="col-md-12">

            <div class="form-group">

                <label>検索条件</label>

                <select name="select_stock" id="select_stockid">


                    @if (ViewBag.select_stock == null)
                    {
                        <option value=1>証券コード</option>
                        <option value=2>証券銘柄</option>
                    }


                    @if (ViewBag.select_stock == "1")
                    {

                        <option value=1 selected>証券コード</option>
                        <option value=2>証券銘柄</option>
                    }
                    @if (ViewBag.select_stock == "2")
                    {
                        <option value=1>証券コード</option>
                        <option value=2 selected>証券銘柄</option>
                    }

                </select>

            </div>

            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-btn">
                        <label>Search</label>

                        <input type="text" class="form-control" id="search" name="search" value="@(ViewBag.search ?? String.Empty)" />
                        <br />
                        <br />
                        @*検索ボタン(submit複数)*@
                        <input type="submit" value="Search" onclick="BtnKensakuClick()" class="btn btn-success mr-2" />

                        @*新規作成ボタン*@
                        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })

                    </span>
                </div>
            </div>
        </div>
    </div>
}




    @if (ViewBag.kassei == 1)

    {
        <input type="submit" value="FileOutput" class="btn btn-success mr-2" id="fileoutputclick"/>
    }
    else
    {
        <input type="submit" value="FileOutput" class="btn btn-success mr-2" id="fileoutputclick"  disabled />
    }

    <br />







    @if (Model != null)
    {

        <table class="table table-bordered table-hover" id="tblstock" name="ntblstock">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Stock_Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Stock_Name)
                </th>
                <th>action</th>
            </tr>



            @foreach (var item in Model)
            {
                <tr id="test">
                    <td>
                        @item.Stock_Id
                    </td>
                    <td>
                        @item.Stock_Name
                    </td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Stock_Id }) 
                        @Html.ActionLink("Delete", "Delete", new { id = item.Stock_Id })
                    </td>
                </tr>
            }

        </table>


       
        <ui class="pagination">
            @{
                int numberPage = ViewBag.numberPage;
                int pageCurrent = ViewBag.pageCurrent;

                if (pageCurrent > 1)
                {
                    int prepage = pageCurrent - 1;
                    <li class="active"><a href="?page=@prepage">Prepage</a></li>
                }

                int i;

                for (i = 1; i <= numberPage; i++)
                {
                    if (i == pageCurrent)
                    {
                        <li class="active"><a href="?page=@i">@i</a></li>
                    }
                    else
                    {
                        <li><a href="?page=@i">@i</a></li>
                    }
                }

                if (pageCurrent >= 1 && pageCurrent < numberPage)
                {
                    int nextpage = pageCurrent + 1;
                    <li class="active"><a href="?page=@nextpage">NextPage</a></li>
                }

            }
        </ui>
    }






        <script type="text/javascript">


            $('#fileoutputclick').click(function () {

                //var td = $('td').text();

                var td = $('td').closest('tr');

                td = $(td).text();

                alert(td);

         
              
                var obj = {
                    Td: td,
                }

                SubmitForm(obj);
                   //SubmitForm();

        });

            function SubmitForm(obj) {
                $.ajax({
                    url: "/Stock/FileOutput",
                    method: "POST",
                    data: obj,

                    success: function (data) {
                        console.log(data);
                        //data = JSON.parse(data);
                        //console.log(data);
                        //alert(data);
                        alert("出力完了しました");

                    },
                    error: function (err) {
                        console.log(err);
                        console.log("error");
                    },
                })
            }



            @*function SubmitForm() {
                $.ajax({
                    url: "/Stock/FileOutput",
                    method: "POST",
                    dataType: 'JSON',
                    data: function (param) {
                        param = "@ViewBag.stocks";
                    }

                    
                })
            }*@





        </script>